name = "Game2048Core"
uuid = "449ebaaf-06bc-4dda-9a3f-b1c40666d086"
authors = ["ZJ Dai <zhuojia.dai@gmail.com> and contributors"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
